### ISSUE TITLE
"include()" is not including some references if part of the include is named like another reference

### ISSUE THREAD

**Issue by idmedia-kaiser** [contentstack/datasync-filesystem-sdk#10]
`Stack.contentType("account_defaultpage").entries().include(["back_link.reference","content.content_link.reference"]).find()`
will not include the reference for content.content_link.reference.
If I remove "back_link.reference", it works. 

I could narrow it down to `getReferencePath` in stack.ts
Because the if path is taken instead of the else. 
`if (path.length !== includePath.length) {
	subPath = subStr;
	pendingPath.push(includePath.slice(path.length + 1));
}
else {
	subPath = includePath;
}`
Added related _contents content to reproduce this.
[_contents.zip](https://github.com/contentstack/datasync-filesystem-sdk/files/9633565/_contents.zip)

When it comes to check "content_link.reference" it matches with "content" and therefore "link.references" is pushed instead of "content_link.reference" because there is also a reference called "content"

**Comment by vkalta** [comment]
@idmedia-kaiser Will it be possible for you to share the stack credentials with me at vikram.kalta@contentstack.com. Let me try this out at my end and revert.
Thanks.

**Comment by idmedia-kaiser** [comment]
I wrote added you to the mail for the corresponding isssue I filed with the support. But I also added a minimum example in the ZIP file added to this issue to reproduce it with

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , we have fixed this issue and released it. Please check and confirm, we will close this issue upon your confirmation.

**Comment by idmedia-kaiser** [comment]
Hi @vkalta , bugfix looks good
