### ISSUE TITLE
Image property returning uid instead of null, if image was not published yet.

### ISSUE THREAD

**Issue by idmedia-kaiser** [contentstack/datasync-filesystem-sdk#11]
### Scenario 

1. Create a new entry of a content type that includes an image entry
2. Publish the new entry WITHOUT references, so the image itself is not published. 

ContentStack API will return "null" for that image when querying that content type
`"image": null`
DataSync API returns the uid of the referenced image 
`"image": "blt5ec250ecf650b59b"`

This breaks some logic because "null" or "undefined" checks fail because the value is for example "blt5ec250ecf650b59b" instead of "null". 

Same happens when you "unpublish" the image without publishing the content type where its referenced.

**Comment by vkalta** [comment]
Hi @idmedia-kaiser, is the image null returned by delivery or management api?

**Comment by vkalta** [comment]
@idmedia-kaiser I have replicated the issue at my end. Will rectify the issue asap and revert.
Thanks.

**Comment by idmedia-kaiser** [comment]
Hi @vkalta what about this issue? Any updates?

**Comment by vkalta** [comment]
Hi @idmedia-kaiser, for this issue we are currently working with other teams internally to get this fixed. We will keep you updated.
Thanks

**Comment by idmedia-kaiser** [comment]
Hi @vkalta any update on this?

**Comment by netrajpatel** [comment]
Hi @idmedia-kaiser,
We are really sorry, but we are still waiting to get the fix, and it is expected to get it done by January.
We will keep you posted on this.

**Comment by idmedia-kaiser** [comment]
Any update here? We also have an open support ticket #00021450 for this

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , thanks for your patience. This should be fixed now. Can you please try and check again? Image uid should be null if it is deleted or unpublished.

**Comment by idmedia-kaiser** [comment]
@vkalta Thanks, just tested it by creating a new content type with a new image, publishing, and then just deleting the image from the assets. The image returns now as null in datasync. Thanks. Issue solved
