### ISSUE TITLE
projections in configuration not working as described

### ISSUE THREAD

**Issue by idmedia-kaiser** [contentstack/datasync-filesystem-sdk#12]
According to the documentation 
projections | object | {_content_type_uid: 0} | Optional Keys that by default would be removed from results. Pass key: 0 to remove, key: 1 to override the existing..
-- | -- | -- | --

it should be possible to pass 1, to active the field again. But it has no effect, because the check only checks if the property is present, it doesn't check the value

`this.projections = Object.keys(this.contentStore.projections);`
This gets all projections regardless if 0 or 1

`result.docs.forEach((doc) => {
	this.projections.forEach((key) => {
		if (doc.hasOwnProperty(key)) {
			delete doc[key];
		}
	});
});`
This only checks the "key" regardless if the value is 0 or 1.

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , we have fixed this issue and released it. Please check and confirm, we will close this issue upon your confirmation.

**Comment by idmedia-kaiser** [comment]
Hi @vkalta , if you don't pass any "only" or "except" it will take the keys from projections as except
Because of this code
`    if (!this.q.hasOwnProperty('except') && !this.q.hasOwnProperty('only')) {
      const keys = Object.keys(this.contentStore.projections)
      this.q.except = keys
    }`

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , I will check this with the team internally and revert.
Thanks

**Comment by idmedia-kaiser** [comment]
Hi @vkalta , you don't need to revert, as those changes are fine, but they don't cover every use case.
I found two more places and added a filter call locally, it works as expected
except function, it should only add the projections with value 0 to the except
`  public except(fields) {
    if (
      fields &&
      typeof fields === "object" &&
      fields instanceof Array &&
      fields.length
    ) {
      this.q.except = [];
      const keys = Object.keys(this.contentStore.projections).filter(
        (key) => this.contentStore.projections[key] === 0
      );
      this.q.except = keys.concat(fields);
      return this;
    }
    throw new Error("Kindly provide valid parameters for .except()!");
  }`

In preProcess, this is neccessary if you don't use except and only, otherwise it still removes projections with regardless of the value

`    if (!this.q.hasOwnProperty("except") && !this.q.hasOwnProperty("only")) {
      const keys = Object.keys(this.contentStore.projections).filter(
        (key) => this.contentStore.projections[key] === 0
      );
      this.q.except = keys;
    }	
`

Please have a look

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , thanks for your patience. We have fixed the issue in the latest version. Please check and confirm.

**Comment by idmedia-kaiser** [comment]
Hi Vikram,

The changes for 1.0.4 where only done in the stack.ts, but not compiled, so its not part of the dist-folder and has therefore no effect.

Furthermore, could you publish the package to NPM?

BR
Benji

Von: Vikram Kalta ***@***.***>
Gesendet: Dienstag, 13. Dezember 2022 17:22
An: contentstack/datasync-filesystem-sdk ***@***.***>
Cc: Benjamin Kaiser ***@***.***>; Mention ***@***.***>
Betreff: Re: [contentstack/datasync-filesystem-sdk] projections in configuration not working as described (Issue #12)


Hi @idmedia-kaiser<https://github.com/idmedia-kaiser> , thanks for your patience. We have fixed the issue in the latest version. Please check and confirm.

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , apologies for the inconvenience and delay in the response. This is planned to be released next week. I will keep you posted. :)
Thanks

**Comment by idmedia-kaiser** [comment]
@vkalta Any update here?

**Comment by vkalta** [comment]
Hi @idmedia-kaiser, sorry for the delayed response, thanks for your patience. This is now released and available on version 1.0.5. Please check and confirm from your side if the changes are working for you.
Thanks

**Comment by idmedia-kaiser** [comment]
Hi,

I don’t see any release or tag for 1.0.5
https://github.com/contentstack/datasync-filesystem-sdk/releases
I see it was merged, but not released

Von: Vikram Kalta ***@***.***>
Gesendet: Freitag, 13. Januar 2023 12:15
An: contentstack/datasync-filesystem-sdk ***@***.***>
Cc: Benjamin Kaiser ***@***.***>; Mention ***@***.***>
Betreff: Re: [contentstack/datasync-filesystem-sdk] projections in configuration not working as described (Issue #12)


Hi @idmedia-kaiser<https://github.com/idmedia-kaiser>, sorry for the delayed response, thanks for your patience. This is now released and available on version 1.0.5. Please check and confirm from your side if the changes are working for you.
Thanks

**Comment by idmedia-kaiser** [comment]
Hi @vkalta hi @netrajpatel thanks for the release, but the additional change from @netrajpatel  broke it again...

`TypeError: localePaths.hasOwnProperty is not a function`

Change in https://github.com/contentstack/datasync-filesystem-sdk/commit/e565f7fcabda3e7924342a0ce5d447d0ff130d6b
```
- const localePaths = {};
+ const localePaths = Object.create(null);
```

**Comment by netrajpatel** [comment]
Hi @idmedia-kaiser,
Sorry for the delay in response, we are looking into this issue you reported, to investigate more, may I know what version of NodeJS you are using?

Also, for now, we do not have any plan to publish the package on NPM, I will check the feasibility and come again after some time.

**Comment by idmedia-kaiser** [comment]
Hi @netrajpatel we are using
NodeJS - v16.13.1

**Comment by idmedia-kaiser** [comment]
@netrajpatel Any update?

**Comment by netrajpatel** [comment]
Hi @idmedia-kaiser,
We are working on a fix and will let you know once this is available after release.
Sorry for the delay in the release.

**Comment by abhinav-from-contentstack** [comment]
> Hi @vkalta hi @netrajpatel thanks for the release, but the additional change from @netrajpatel broke it again...
> 
> `TypeError: localePaths.hasOwnProperty is not a function`
> 
> Change in [e565f7f](https://github.com/contentstack/datasync-filesystem-sdk/commit/e565f7fcabda3e7924342a0ce5d447d0ff130d6b)
> 
> ```
> - const localePaths = {};
> + const localePaths = Object.create(null);
> ```
> 
> (If i change it back it {} the other changes work as expected) Please provide a new release with a bugfix. And again the question if you can publish it to NPM as a package

Hi @idmedia-kaiser, we have added a fix for this issue in our recent [release](https://github.com/contentstack/datasync-filesystem-sdk/releases/tag/v1.0.6). Please have a look and let us know if it works for you, thank you.

**Comment by idmedia-kaiser** [comment]
Hi @abhinav-from-contentstack  I can confirm the issue itself, and the bug that came in 1.0.5, are no longer present and 1.0.6 works as expected. Closing the issue
