### ISSUE TITLE
Datasync runtime exception if nexted reference is not published

### ISSUE THREAD

**Issue by idmedia-kaiser** [contentstack/datasync-filesystem-sdk#20]
If a content type with a reference, which itself includes another reference, is published, but a nested reference is not. This causes a runtime exception

TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at Stack.<anonymous> (/home/node/app/node_modules/datasync-filesystem-sdk/dist/stack.js:1556:61)
    at Generator.next (<anonymous>)
    at fulfilled (/home/node/app/node_modules/datasync-filesystem-sdk/dist/stack.js:11:58)"

Because the object that is checked here `oldObjectPointerList[i].path[e]`
https://github.com/contentstack/datasync-filesystem-sdk/blob/81fa6af6be959562863caa3b21ac45b2e7d77352/src/stack.ts#L1759

is null if not all references are published. This happens if you use the `blogQuery.includeReferences()` which will include all nested references

**Comment by idmedia-kaiser** [comment]
HI @vkalta @netrajpatel @abhinav-from-contentstack , we got a new issue with not published references. Workaround is to make sure all references are published. I guess this is related to the contentstack API changes, because it broke also on PROD enviroment, where we didn't update the SDK yet

**Comment by antonyagustine** [comment]
Hi @idmedia-kaiser,

We try to replicate it at our end to understand more about the issue. Unfortunately not able to reproduce it. Could you please provide us with additional information about the issue? like the sample schema and sample query used to reproduce it.

Thanks,

CC @netrajpatel @vkalta

**Comment by idmedia-kaiser** [comment]
Hi @antonyagustine 

- Create a new content type "TestPage" as  "web page" mulitple
- Create a new content type - RefTest, with a reference field that can reference to TestPage
- Create an instance of TestPage 
- Create an instance of RefTest and link the TestPage instance in the reference field
- Publish RefTest WITHOUT references
- Query the RefTest contenttype  via datasync including `blogQuery.includeReferences();`

**Comment by idmedia-kaiser** [comment]
It could also be related to your API changes, and NOT republishing everything so that there where null values possible because of some "dirty data" ?

**Comment by antonyagustine** [comment]
Hi @idmedia-kaiser ,

Thanks for your input. We've also tried the same steps to reproduce it, but we were not able to get the same issue.

It might be an API issue as well as you mentioned, but we can't say for sure, and it can be a data-related issue as well. The published data which you working with are old data.?

With the latest source/new stack data, we are not able to reproduce the reported issue.

**Comment by idmedia-kaiser** [comment]
Hi @antonyagustine, I will close this issue for now, as I can't reproduce it as well. I assume it was related to the API Changes but was fixed with a new publication
