### ISSUE TITLE
Missing reference fields for nested reference fields when using .include()

### ISSUE THREAD

**Issue by idmedia-kaiser** [contentstack/datasync-filesystem-sdk#21]
There is a problem in the internal **getReferencePath** function

We have several content types where we have a "form" reference field, which itself has "fields" reference field.
When trying to fetch the fields entries its not working because the check is not working correctly for nested fields.
Simplified examples of the two content types
`{
	"_content_type_uid": "pin_reset_page",
	"locale": "de-de",
	"unknown_customer": {
		"form": [
			{
				"uid": "blt208e828db2bc1155",
				"_content_type_uid": "form"
			}
		]
	},
	"updated_at": "2022-11-25T12:12:39.528Z",
	"url": "/unified-mpp-pin-reset-page"
}

{
	"_content_type_uid": "form",
	"locale": "de-de",
	"additional_text": "",
	"fields": [{ "uid": "bltd0a76355d956c079", "_content_type_uid": "input_field" }],
	"headline": "Jugendschutz-PIN vergessen?",
	"tags": []

}
{
		"_content_type_uid": "input_field",
		"rules": [{ "uid": "blt58b06a7fe2b613b5", "_content_type_uid": "validation_rule" }],
		"tags": [],
}
`

So when we call
`blogQuery.includes(["unknown_customer.form", "unknown_customer.form.fields", " "unknown_customer.form.fields.rules"]);`

We have the following values in the getReferencePath
`
currentInclude =  [
  'unknown_customer',
  'unknown_customer.form',
  'unknown_customer.form.fields',
  'unknown_customer.form.fields.rules'
] 
entryReferences = {
  'unknown_customer.form': [ 'form' ]
}
`
when we come to 
https://github.com/contentstack/datasync-filesystem-sdk/blob/81fa6af6be959562863caa3b21ac45b2e7d77352/src/stack.ts#L1447
the unknown_customer.form works find and and the "form" reference is added. But then the "unknown_customer.form.fields" gets handled the same way because the _subStrArr_ is "unknown_customer" , same as before, where it needs to be "unknown_customer.form" because then the "fields" get added to the pending paths, same basically for the rules

This is a side effect of 
https://github.com/contentstack/datasync-filesystem-sdk/pull/13/files#diff-1ebd2ec0fa0f7b0aac61f8683a96f14f9ba2f36cc068918c16b6c3aaf8418e0a

the part where the includePaths are checked

Just tested it with the old version, and that works. 
But of course there was the other issue https://github.com/contentstack/datasync-filesystem-sdk/issues/10 that then breaks again

So we need a more sophisticated implementation here

I guess the problem is deeply nested references

@vkalta @netrajpatel @abhinav-from-contentstack

**Comment by idmedia-kaiser** [comment]
@antonyagustine FYI

**Comment by idmedia-kaiser** [comment]
I'm still comparing the DataSync responses and the bugfix added for https://github.com/contentstack/datasync-filesystem-sdk/pull/13/files#diff-1ebd2ec0fa0f7b0aac61f8683a96f14f9ba2f36cc068918c16b6c3aaf8418e0a is breaking more then its fixing :/

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , sorry for the inconvenience. We are currently checking the issue and will share an update asap.
Thanks

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , if possible can you please email me the contents folder at vikram.kalta@contentstack.com?

**Comment by idmedia-kaiser** [comment]
Done, hope you got it

**Comment by vkalta** [comment]
@idmedia-kaiser Thanks.

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , a fix for this issue is released. Can you check and confirm please?
Thanks

**Comment by idmedia-kaiser** [comment]
Lgtm! All our test cases work now. Thanks
