### ISSUE TITLE
[BUG] DataSync SDK throws an exception, when you query a content type that has not yet published references

### ISSUE THREAD

**Issue by idmedia-kaiser** [contentstack/datasync-filesystem-sdk#28]
We get the following exception, when we query a content type including references, and one (or more) references are not yet published.
`TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at Stack.<anonymous> (/home/node/app/node_modules/datasync-filesystem-sdk/dist/stack.js:1208:49)
    at Generator.next (<anonymous>)
    at fulfilled (/home/node/app/node_modules/datasync-filesystem-sdk/dist/stack.js:11:58)`

We are using
blogQuery.include([
                "buttons",
                "content",
                "content.deal_items",
                "content.deal_items.image16_9.channel",
                "content.deal_items.image16_9.competition",
                "content.deal_items.default_comparison",
                "content.deal_items.secondary_button.reference",
                "content.deal_items.filter_tags",
                "content.rail.manually.content_link.reference",
                "content.primary_button.reference",
                "content.secondary_button.reference"
            ])

And the content type instance looks like this
`{
  "title": "Deal Selection - Deal Cards",
  "headline": "",
  "subheadline": "",
  "text": "",
  "config": {
    "variant": "dealCard",
    "mobile": "stacked"
  },
  "deal_items": [
    {
      "uid": "blt3ea1b0c7d505e185",
      "_content_type_uid": "deal_item"
    },
    {
      "uid": "blt7cbdd8f42d317990",
      "_content_type_uid": "deal_item"
    },
    {
      "uid": "blt4019d2d57c5d735d",
      "_content_type_uid": "deal_item"
    },
    {
      "uid": "blt21af4abc87ccba18",
      "_content_type_uid": "deal_item"
    },
    {
      "uid": "blt7e20357fb7549664",
      "_content_type_uid": "deal_item"
    },
    {
      "uid": "bltacb034455a73cb53",
      "_content_type_uid": "deal_item"
    },
    {
      "uid": "blt587c8e2ad2466b21",
      "_content_type_uid": "deal_item"
    },
    {
      "uid": "blt08d2a4624e84e497",
      "_content_type_uid": "deal_item"
    }
  ],
  "tags": [],
  "locale": "de-de",
  "_in_progress": false,
  "_embedded_items": {
    "text": []
  },
  "publish_details": [

  ],
  "_rules": []
}`

One of the deal_item was not published and then we got this exception. It was solved by publishing the missing item, but the SDK should not throw an error in that case

**Comment by netrajpatel** [comment]
Hey @idmedia-kaiser,
You are right the SDK should not raise the exception rather it should handle this in a better way.
Thanks for raising this out we will surely look into this in some time and will update you.
